/**
 * Auto-generated by scripts/fetch-myoperator-contact-links.ts
 * Contains user identifiers — do not commit to public repos.
 * Optional argv: output path (default: links.js in user-service root)
 */
module.exports = {
  "generatedAt": "2026-05-04T04:49:36.125Z",
  "count": 0,
  "contacts": [],
  "contactIds": []
};
